# -*- coding: utf-8 -*-
"""clase0808.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uj38sephmjh6MIU6c7AtklSO1gdxvwaf
"""

import matplotlib.pyplot as plt
import numpy as np


#presente = 0 
# direccion = f(y,t)

#presente = 0 
# direccion = f(y,t)
def get_euler(t0, tf, presente, direccion, dt, *args):  #t0, tf, presente, direccion, dt , *args
  values = []
  tiempos= []
  while t0 < tf:
    presente = presente + dt * direccion(t0,presente, *args)
    values.append(presente)
    tiempos.append(t0)
    t0 = t0 + dt
  values = np.array(values)
  tiempos = np.array(tiempos)
  return values,tiempos


def getRungeKutta(t0, tf, ci, direccion,dt, *args): #ci cond ini
  values = []
  times= []
  while t0 < tf:
    f1 = direccion(t0,ci, *args)
    f2= direccion(t0+(dt/2),ci + (dt/2)*f1, *args)
    f3= direccion(t0+(dt/2),ci + (dt/2)*f2,*args)
    f4= direccion(t0+dt,ci + dt*f3, *args)

    ci =ci + dt/6 *(f1+2*f2+2*f3+f4)
    values.append(ci)
    times.append(t0)
    t0 = t0 + dt
  values = np.array(values)
  times = np.array(times)
  return values,times